---
  - name: Test the services running and registered
    hosts: servers
    remote_user: ubuntu
    become: yes
  - name: collect facts about system services
    service_facts:
    register: services_state
  - name: Debug
    debug:
    var: services_state